@startuml
  skinparam linetype ortho
  skinparam classAttributeIconSize 0
  hide circle

  interface StateStore {
    +name(): String
    +init(StateStoreContext, StateStore): void
    +flush(): void
    +close(): void
    +persistent(): boolean
    +isOpen(): boolean
    +query(Query<R>, PositionBound, QueryConfig): QueryResult<R>
    +getPosition(): Position
  }

  interface ReadOnlyKeyValueStore<K,V> {
    +get(K): V
    +range(K, K): KeyValueIterator<K,V>
    +reverseRange(K, K): KeyValueIterator<K,V>
    +all(): KeyValueIterator<K,V>
    +reverseAll(): KeyValueIterator<K,V>
    +prefixScan(P, PS): KeyValueIterator<K,V>
    +approximateNumEntries(): long
  }

  interface KeyValueStore<K,V> {
    +put(K, V): void
    +putIfAbsent(K, V): V
    +putAll(List<KeyValue<K,V>>): void
    +delete(K): V
  }

  interface TimestampedKeyValueStore<K,V> {
    .. inherits all methods ..
    .. value type: ValueAndTimestamp<V> ..
  }

  interface VersionedKeyValueStore<K,V> {
    +put(K, V, long): long
    +delete(K, long): VersionedRecord<V>
    +get(K): VersionedRecord<V>
    +get(K, long): VersionedRecord<V>
  }

  interface ReadOnlyWindowStore<K,V> {
    +fetch(K, long): V
    +fetch(K, Instant, Instant): WindowStoreIterator<V>
    +fetch(K, K, Instant, Instant): KeyValueIterator<Windowed<K>,V>
    +backwardFetch(K, Instant, Instant): WindowStoreIterator<V>
    +backwardFetch(K, K, Instant, Instant): KeyValueIterator<Windowed<K>,V>
    +all(): KeyValueIterator<Windowed<K>,V>
    +backwardAll(): KeyValueIterator<Windowed<K>,V>
    +fetchAll(Instant, Instant): KeyValueIterator<Windowed<K>,V>
    +backwardFetchAll(Instant, Instant): KeyValueIterator<Windowed<K>,V>
  }

  interface WindowStore<K,V> {
    +put(K, V, long): void
  }

  interface TimestampedWindowStore<K,V> {
    .. inherits all methods ..
    .. value type: ValueAndTimestamp<V> ..
  }

  interface ReadOnlySessionStore<K,AGG> {
    +fetch(K): KeyValueIterator<Windowed<K>,AGG>
    +fetch(K, K): KeyValueIterator<Windowed<K>,AGG>
    +backwardFetch(K): KeyValueIterator<Windowed<K>,AGG>
    +backwardFetch(K, K): KeyValueIterator<Windowed<K>,AGG>
    +findSessions(K, long, long): KeyValueIterator<Windowed<K>,AGG>
    +backwardFindSessions(K, long, long): KeyValueIterator<Windowed<K>,AGG>
    +fetchSession(K, long, long): AGG
  }

  interface SessionStore<K,AGG> {
    +put(Windowed<K>, AGG): void
    +remove(Windowed<K>): void
  }

  ' Inheritance relationships
  StateStore <|--- KeyValueStore
  ReadOnlyKeyValueStore <|-- KeyValueStore
  StateStore <|-- VersionedKeyValueStore
  KeyValueStore <|-- TimestampedKeyValueStore

  StateStore <|---- WindowStore
  ReadOnlyWindowStore <|-- WindowStore
  WindowStore <|-- TimestampedWindowStore

  StateStore <|--- SessionStore
  ReadOnlySessionStore <|-- SessionStore

  note bottom of KeyValueStore : KSML: type: keyValue
  note bottom of TimestampedKeyValueStore : KSML: type: keyValue\ntimestamped: true
  note bottom of VersionedKeyValueStore : KSML: type: keyValue\nversioned: true
  note right of WindowStore : KSML: type: window
  note bottom of TimestampedWindowStore : KSML: type: window\ntimestamped: true
  note bottom of SessionStore : KSML: type: session

  @enduml
