# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/heads/main/docs/ksml-language-spec.json

streams:
  raw_sensor_readings:
    topic: iot_sensor_readings
    keyType: string
    valueType: json

  edge_processed_readings:
    topic: edge_processed_readings
    keyType: string
    valueType: json

pipelines:
  edge_preprocessing:
    from: raw_sensor_readings
    via:
      - type: filter
        if:
          code: |
            # Forward temperatures outside comfortable range (more data for cloud analytics)
            temp = value.get("readings", {}).get("temperature")
            return temp is not None and (temp < 18.0 or temp > 26.0)
      - type: transformValue
        mapper:
          code: |
            # Simplify payload for transmission
            return {
              "id": value.get("device_id"),
              "ts": value.get("timestamp"),
              "loc": value.get("location", {}).get("room"),
              "temp": value.get("readings", {}).get("temperature"),
              "hum": value.get("readings", {}).get("humidity")
            }
    to: edge_processed_readings
