functions:
  generate_sales_event:
    type: generator
    globalCode: |
      import random
      import time
      product_counter = 0
      products = ["laptop", "phone", "tablet", "monitor", "keyboard", "mouse", "headphones", "webcam"]
      regions = ["North", "South", "East", "West", "Central"]
    code: |
      global product_counter, products, regions
      
      # Cycle through products
      product = products[product_counter % len(products)]
      product_counter += 1
      
      # Generate sale event
      value = {
        "product_id": product,
        "region": random.choice(regions),
        "amount": round(random.uniform(10, 1000), 2),
        "quantity": random.randint(1, 5),
        "timestamp": int(time.time() * 1000)
      }
      
      # Use product_id as key
      key = product
    expression: (key, value)
    resultType: (string, json)

producers:
  sales_producer:
    generator: generate_sales_event
    interval: 2s
    to:
      topic: retail_sales
      keyType: string
      valueType: json