functions:
  generate_transaction:
    type: generator
    globalCode: |
      import random
      import time
      account_counter = 0
      accounts = ["ACC001", "ACC002", "ACC003", "ACC004", "ACC005"]
    code: |
      global account_counter, accounts
      
      # Cycle through accounts
      account = accounts[account_counter % len(accounts)]
      account_counter += 1
      
      # Generate transaction amount (in cents to avoid float issues)
      amount_cents = random.randint(100, 50000)
      
      # Create human-readable JSON structure
      value = {
        "account_id": account,
        "amount_cents": amount_cents,
        "amount_dollars": round(amount_cents / 100.0, 2),
        "transaction_id": f"TXN{account_counter:06d}",
        "timestamp": int(time.time() * 1000)
      }
      
      # Use account_id as key
      key = account
    expression: (key, value)
    resultType: (string, json)

producers:
  transaction_producer:
    generator: generate_transaction
    interval: 1s
    to:
      topic: financial_transactions
      keyType: string
      valueType: json