functions:
  generate_payment:
    type: generator
    globalCode: |
      import random
      import time
      account_counter = 0
      accounts = ["ACC001", "ACC002", "ACC003", "ACC004", "ACC005", "ACC006"]
    code: |
      global account_counter, accounts
      
      # Cycle through accounts
      account = accounts[account_counter % len(accounts)]
      account_counter += 1
      
      # Generate payment event
      value = {
        "account_id": account,
        "amount": round(random.uniform(5.0, 500.0), 2),
        "currency": "USD",
        "timestamp": int(time.time() * 1000)
      }
      
      # Use account_id as key
      key = account
    expression: (key, value)
    resultType: (string, json)

producers:
  payment_producer:
    generator: generate_payment
    interval: 1s
    to:
      topic: payment_stream
      keyType: string
      valueType: json