streams:
  user_logins:
    topic: user_login_events
    keyType: string  # User ID
    valueType: json  # Login details

  user_actions:
    topic: user_action_events
    keyType: string  # User ID
    valueType: json  # Action details

  user_logouts:
    topic: user_logout_events
    keyType: string  # User ID
    valueType: json  # Logout details

  user_sessions:
    topic: user_session_events
    keyType: string  # User ID
    valueType: json  # Complete session information

functions:
  correlate_session_events:
    type: valueTransformer
    code: |
      event_type = value.get("event_type")

      # Get current session state
      session = state_store.get(key + "_session")
      if session is None:
        session = {"events": []}

      # Add this event to the session
      event_copy = value.copy()
      event_copy["processed_time"] = int(time.time() * 1000)
      session["events"].append(event_copy)

      # Update session based on event type
      if event_type == "login":
        session["login_time"] = value.get("timestamp")
        session["device"] = value.get("device")
        session["ip_address"] = value.get("ip_address")
        session["status"] = "active"
      elif event_type == "action":
        session["last_activity_time"] = value.get("timestamp")
        session["last_action"] = value.get("action_type")
      elif event_type == "logout":
        session["logout_time"] = value.get("timestamp")
        session["status"] = "completed"
        session["duration_ms"] = session["logout_time"] - session.get("login_time", 0)

        # Return the complete session and clear state
        result = session.copy()
        state_store.delete(key + "_session")
        return result

      # Update session state and don't emit for incomplete sessions
      state_store.put(key + "_session", session)
      return None
    stores:
      - session_state_store

pipelines:
  process_login_events:
    from: user_logins
    mapValues: correlate_session_events
    filter: is_not_null
    to: user_sessions

  process_action_events:
    from: user_actions
    mapValues: correlate_session_events
    filter: is_not_null
    to: user_sessions

  process_logout_events:
    from: user_logouts
    mapValues: correlate_session_events
    filter: is_not_null
    to: user_sessions
