# --- step 1: build the code on GraalVM
FROM ghcr.io/graalvm/graalvm-ce:21.2.0 AS builder
MAINTAINER Axual <maintainer@axual.io>
RUN curl -O https://dlcdn.apache.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz \
  && tar xvf apache-maven-3.8.3-bin.tar.gz \
  && gu install python
ADD . /project_dir
RUN cd project_dir && /apache-maven-3.8.3/bin/mvn clean package

# --- step 2: build GraalVM image with compiled code
FROM ghcr.io/graalvm/graalvm-ce:21.2.0

RUN mkdir -p "/opt/ksml/libs"  \
  && chown -R 1024:users /opt \
  && gu -A install python

COPY --chown=1024 --from=builder /project_dir/ksml-runner/target/libs/ /opt/ksml/libs/
COPY --chown=1024 --from=builder /project_dir/ksml-runner/target/ksml-runner*.jar /opt/ksml/ksml.jar

WORKDIR /opt/ksml
USER 1024
ENTRYPOINT ["java", "-jar", "/opt/ksml/ksml.jar"]
