FROM registry.access.redhat.com/ubi8/openjdk-17:1.14 as builder
USER root
ADD . /project_dir
RUN cd /project_dir/ksml-example-producer && mvn clean package \
    && mkdir -p /opt/java/libs \
    && cp -rf target/libs/* /opt/java/libs/ \
    && cp -rf target/ksml-example-producer*.jar /opt/java/ksml-example-producer.jar

FROM registry.access.redhat.com/ubi8/openjdk-17-runtime:1.14
MAINTAINER Axual <maintainer@axual.io>
USER root
COPY --chown=1024 --from=builder /opt/java/ /opt/java/
RUN chown -R 1024:users /opt
WORKDIR /opt/java
USER 1024
ENTRYPOINT ["java", "-jar", "/opt/java/ksml-example-producer.jar"]
