# --- step 1: build the code on GraalVM
FROM ghcr.io/graalvm/graalvm-ce:21.2.0 AS builder
MAINTAINER Axual <maintainer@axual.io>
RUN curl -O https://dlcdn.apache.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz \
  && tar xvf apache-maven-3.8.3-bin.tar.gz \
  && gu install python
ADD . /project_dir
RUN cd project_dir && /apache-maven-3.8.3/bin/mvn clean package

# --- step 2: build GraalVM image with compiled code
FROM redhat/ubi8:8.4-206.1626828523
ENV JAVA_HOME=/opt/graalvm
ENV PATH=/opt/graalvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# --- specify one of [ksml-runner, ksml-runner-axual]; ksml-runner is default
ARG runner=ksml-runner
RUN echo Building runner: $runner

RUN mkdir -p "/opt/ksml/libs"  \
  && curl -k -L -o "/tmp/graalvm.tgz" "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java11-linux-amd64-21.2.0.tar.gz" \
  && tar -xzf /tmp/graalvm.tgz -C "/opt" \
  && mv /opt/graalvm* /opt/graalvm \
  && chown -R 1024:users /opt \
  && rm -rf /tmp/graalvm.tgz \
  && /opt/graalvm/bin/gu -A install python

COPY --chown=1024 --from=builder /project_dir/$runner/target/libs/ /opt/ksml/libs/
COPY --chown=1024 --from=builder /project_dir/$runner/target/ksml-runner*.jar /opt/ksml/ksml.jar

WORKDIR /opt/ksml
USER 1024
ENTRYPOINT ["java", "-jar", "/opt/ksml/ksml.jar"]
