site_name: KSML Documentation
site_author: Axual
site_description: Documentation for the KSML project

site_dir: _site
theme:
  name: material
  features:
    - content.code.copy

plugins:
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: true
      trailing_newlines: true
      comments: false
      rewrite_relative_urls: true
      heading_offset: 0
      recursive: true
  - autorefs:
      resolve_closest: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/installation.md
      - Understanding KSML: getting-started/introduction.md
  - Core Concepts:
      - Overview: core-concepts/index.md
      - Data Types: reference/data-type-reference.md
      - Notations: reference/notation-reference.md
      - Functions: core-concepts/functions.md
      - Pipelines: core-concepts/pipelines.md
      - Operations: core-concepts/operations.md
      - Error Handling: core-concepts/error-handling.md
      - Advanced Topics: core-concepts/advanced-topics.md
  - Tutorials:
      - KSML Basics Tutorial: getting-started/basics-tutorial.md
      - Beginner Tutorials:
        - Overview: tutorials/beginner/index.md
        - Filtering and Transforming: tutorials/beginner/filtering-transforming.md
        - Different Data Formats: tutorials/beginner/data-formats.md
        - Logging and Monitoring: tutorials/beginner/logging-monitoring.md
      - Intermediate Tutorials:
        - Overview: tutorials/intermediate/index.md
        - Aggregations: tutorials/intermediate/aggregations.md
        - Joins: tutorials/intermediate/joins.md
        - Windowing: tutorials/intermediate/windowing.md
        - Error Handling and Recovery: tutorials/intermediate/error-handling.md
        - State Stores: tutorials/intermediate/state-stores.md
      - Advanced Tutorials:
        - Overview: tutorials/advanced/index.md
        - Complex Event Processing: tutorials/advanced/complex-event-processing.md
        - Custom State Stores: tutorials/advanced/custom-state-stores.md
        - Performance Optimization: tutorials/advanced/performance-optimization.md
        - Integration with External Systems: tutorials/advanced/external-integration.md
        - Advanced Error Handling: tutorials/advanced/advanced-error-handling.md
  - Use Case Guides:
      - Overview: use-cases/index.md
      - Data Transformation: use-cases/data-transformation.md
      - Event-Driven Applications: use-cases/event-driven-applications.md
      - Microservices Integration: use-cases/microservices-integration.md
      - IoT Data Processing: use-cases/iot-data-processing.md
      - Real-time Analytics: use-cases/real-time-analytics.md
      - Fraud Detection: use-cases/fraud-detection.md
  - References:
      - Overview: reference/index.md
      - KSML Language Reference: reference/language-reference.md
      - Stream Types Reference: reference/stream-type-reference.md
      - Data Types Reference: reference/data-type-reference.md
      - Notations Reference: reference/notation-reference.md
      - Functions Reference: reference/function-reference.md
      - Operations Reference: reference/operation-reference.md
      - Configuration Reference: reference/configuration-reference.md
  - Resources:
      - Examples Library: resources/examples-library.md
      - Troubleshooting Guide: resources/troubleshooting.md
      - Migration Guide: resources/migration.md
      - Community and Support: resources/community.md
      - Advanced Installation: getting-started/advanced-installation.md
  - Release Notes: release-notes.md
