site_name: KSML Documentation
site_author: Axual
site_description: Documentation for the KSML project

site_dir: _site
theme:
  name: material
  features:
    - content.code.copy
#theme: mkdocs
#theme: readthedocs

plugins:
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0
      start: "~~~yaml\n"
      end: "~~~\n"
      recursive: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started: tutorials/getting-started/index.md
  - Core Concepts: core-concepts/index.md
  - Tutorials:
      - Basic Tutorials: tutorials/getting-started/basics-tutorial.md
      - Beginner Tutorials: tutorials/beginner/index.md
      - Intermediate Tutorials: tutorials/intermediate/index.md
      - Advanced Tutorials: tutorials/advanced/index.md
  - Use Cases:
      - Real-time Analytics: use-cases/real-time-analytics.md
      - Data Transformation: use-cases/data-transformation.md
      - Event-Driven Applications: use-cases/event-driven-applications.md
      - Microservices Integration: use-cases/microservices-integration.md
      - IoT Data Processing: use-cases/iot-data-processing.md
      - Fraud Detection: use-cases/fraud-detection.md
  - Reference:
      - Types: reference/data-types-reference.md
      - Notations: reference/notation-reference.md
      - Streams: reference/stream-type-reference.md
      - Operations: reference/operation-reference.md
      - Functions: reference/function-reference.md
      - State Stores: reference/store-reference.md
      - Runners: runners.md
  - Language specification: ksml-language-spec.md
  - Release Notes: release-notes.md
