site_name: KSML Documentation
site_author: Axual
site_description: Documentation for the KSML project

site_dir: _site
theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: true
      dedent: true
      trailing_newlines: true
      comments: false
      rewrite_relative_urls: true
      heading_offset: 0
      recursive: true
  - autorefs:
      resolve_closest: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs"]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.details

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quick-start.md
      - Understanding KSML: getting-started/introduction.md
  - Tutorials:
      - Overview: tutorials/index.md
      - KSML Basics Tutorial: getting-started/basics-tutorial.md
      - Beginner Tutorials:
        - Overview: tutorials/beginner/index.md
        - Filtering and Transforming: tutorials/beginner/filtering-transforming.md
        - Different Data Formats: tutorials/beginner/data-formats.md
        - Logging and Monitoring: tutorials/beginner/logging-monitoring.md
      - Intermediate Tutorials:
        - Overview: tutorials/intermediate/index.md
        - Branching: tutorials/intermediate/branching.md
        - Aggregations: tutorials/intermediate/aggregations.md
        - Joins: tutorials/intermediate/joins.md
        - Windowing: tutorials/intermediate/windowing.md
        - Error Handling: tutorials/intermediate/error-handling.md
        - State Stores: tutorials/intermediate/state-stores.md
      - Advanced Tutorials:
        - Overview: tutorials/advanced/index.md
        - Complex Event Processing: tutorials/advanced/complex-event-processing.md
        - Custom State Stores: tutorials/advanced/custom-state-stores.md
        - Performance Optimization: tutorials/advanced/performance-optimization.md
        - Integration with External Systems: tutorials/advanced/external-integration.md
  - Use Case Guides:
      - Overview: use-cases/index.md
      - Data Transformation: use-cases/data-transformation.md
      - Event-Driven Applications: use-cases/event-driven-applications.md
      - IoT Data Processing: use-cases/iot-data-processing.md
      - Real-time Analytics: use-cases/real-time-analytics.md
      - Fraud Detection: use-cases/fraud-detection.md
  - References:
      - Overview: reference/index.md
      - KSML Definition Reference: reference/definition-reference.md
      - Pipeline Reference: reference/pipeline-reference.md
      - Function Reference: reference/function-reference.md
      - Operation Reference: reference/operation-reference.md
      - Data Types and Notations Reference: reference/data-and-formats-reference.md
      - State Store Reference: reference/state-store-reference.md
      - Configuration Reference: reference/configuration-reference.md
  - Release Notes: release-notes.md
