site_name: KSML Documentation
site_author: Axual
site_description: Documentation for the KSML project

site_dir: _site
theme:
  name: material
  features:
    - content.code.copy

plugins:
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: true
      trailing_newlines: true
      comments: false
      rewrite_relative_urls: true
      heading_offset: 0
      recursive: true
  - autorefs:
      resolve_closest: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/installation.md
      - Understanding KSML: getting-started/introduction.md
  - Core Concepts:
      - Overview: core-concepts/index.md
      - Data Types: reference/data-type-reference.md
      - Notations: reference/notation-reference.md
      - Stream Types: reference/stream-type-reference.md
      - Functions: core-concepts/functions.md
      - Pipelines: core-concepts/pipelines.md
      - Operations: core-concepts/operations.md
      - Error Handling: core-concepts/error-handling.md
      - Advanced Topics: core-concepts/advanced-topics.md
  - Tutorials:
      - KSML Basics Tutorial: getting-started/basics-tutorial.md
      - Beginner Tutorials: tutorials/beginner/index.md
      - Intermediate Tutorials: tutorials/intermediate/index.md
      - Advanced Tutorials: tutorials/advanced/index.md
  - Use Case Guides:
      - Overview: use-cases/index.md
      - Data Transformation: use-cases/data-transformation.md
      - Event-Driven Applications: use-cases/event-driven-applications.md
      - Microservices Integration: use-cases/microservices-integration.md
      - IoT Data Processing: use-cases/iot-data-processing.md
      - Real-time Analytics: use-cases/real-time-analytics.md
      - Fraud Detection: use-cases/fraud-detection.md
  - Reference:
      - Overview: reference/index.md
      - KSML Language Reference: reference/language-reference.md
      - Functions Reference: reference/function-reference.md
      - Operations Reference: reference/operation-reference.md
      - Configuration Reference: reference/configuration-reference.md
  - Resources:
      - Examples Library: resources/examples-library.md
      - Troubleshooting Guide: resources/troubleshooting.md
      - Migration Guide: resources/migration.md
      - Community and Support: resources/community.md
      - Advanced Installation: getting-started/advanced-installation.md
  - Release Notes: release-notes.md
