apiVersion: v1
kind: Service
metadata:
  name: {{ include "ksml.fullname" . }}-headless
  labels:
    {{- include "ksml.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ksml.selectorLabels" . | nindent 4 }}
