{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ksml.fullname" . }}-network-policy
spec:
  podSelector:
    matchLabels:
      {{- include "ksml.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- with .Values.networkPolicy.ingress }}
      {{- toYaml . | nindent 2 }}
    {{- end }}
  egress:
    {{- with .Values.networkPolicy.egress }}
      {{- toYaml . | nindent 2 }}
    {{- end }}
{{- end -}}