apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ksml.fullname" . }}-network-policy
spec:
  podSelector:
    matchLabels:
      {{- include "ksml.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      {{- with .Values.networkPolicy.ingress.from }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
  egress:
    - to:
        {{- with .Values.networkPolicy.egress.to }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
