{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" )  .Values.prometheus.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ksml.fullname" . }}
  labels:
    {{- include "ksml.labels" . | nindent 4 }}
    {{- if (.Values.serviceMonitor.labels)  }}
      {{- toYaml .Values.serviceMonitor.labels | nindent  4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
        {{- include "ksml.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
