apiVersion: v1
kind: Service
metadata:
  name: {{ include "ksml.fullname" . }}
  labels:
    {{- include "ksml.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "ksml.selectorLabels" . | nindent 4 }}
