apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ksml.fullname" . }}
  labels:
    {{- include "ksml.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ksml.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "ksml.fullname" . }}-headless
  podManagementPolicy: Parallel
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-runner.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ksml.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ksml.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /ksml
          ports:
            - name: http
              containerPort: {{ .Values.applicationServer.port }}
              protocol: TCP
            {{- if .Values.prometheus.enabled }}
            - name: metrics
              containerPort: {{ .Values.prometheus.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          env:
            - name: "KSML_K8S_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KSML_GROUP_INSTANCE_ID
              value: "$(KSML_K8S_POD_NAME)"
            - name: LOGBACK_CONFIGURATION_FILE
              value: {{ .Values.logging.configFile | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: ksml-config
              mountPath: /ksml
            - name: ksml-logging
              mountPath: /ksml-logging
            - name: ksml-store
              mountPath: /ksml-store
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: ksml-config
          configMap:
            name: {{ include "ksml.fullname" . }}-runner
        - name: ksml-logging
          configMap:
            name: {{ include "ksml.fullname" . }}-logging
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints}}
      topologySpreadConstraints:
      {{- range . }}
        - labelSelector:
            matchLabels:
      {{- include "ksml.selectorLabels" $ | nindent 12 }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: ksml-store
      spec:
        {{- toYaml .Values.store.spec | nindent 8 }}
