functions:
  generate_click:
    type: generator
    globalCode: |
      import random
      import time
      click_counter = 0
      users = ["alice", "bob", "charlie", "diana", "eve"]
      pages = ["/home", "/products", "/about", "/contact", "/checkout"]
    code: |
      global click_counter, users, pages
      
      click_counter += 1
      user_id = random.choice(users)
      
      value = {
        "click_id": f"click_{click_counter:06d}",
        "user_id": user_id,
        "page": random.choice(pages),
        "session_id": f"session_{user_id}_{random.randint(1, 3)}",
        "timestamp": int(time.time() * 1000)
      }
      
      key = user_id
    expression: (key, value)
    resultType: (string, json)

producers:
  click_producer:
    generator: generate_click
    interval: 1s
    to:
      topic: user_clicks
      keyType: string
      valueType: json