# Producer for logging and monitoring tutorial
# Generates simple messages with different importance levels for logging demonstration

functions:
  generate_log_message:
    type: generator
    code: |
      import random
      levels = ["INFO", "WARN", "ERROR", "DEBUG"]
      messages = [
        "System startup completed",
        "Database connection established", 
        "User authentication failed",
        "Cache refresh initiated",
        "Memory usage high",
        "Backup process completed"
      ]
      
      result = {
        "level": random.choice(levels),
        "message": random.choice(messages),
        "timestamp": time.time(),
        "importance": random.randint(1, 10),
        "component": random.choice(["auth", "db", "cache", "backup"])
      }
    expression: result
    resultType: json

producers:
  log_message_producer:
    topic: ksml_logging_input
    key:
      generator:
        expression: "log-" + str(counter)
        resultType: string
    value:
      generator:
        functionRef: generate_log_message
    interval: 2.0s