streams:
  orders:
    topic: new_orders
    keyType: string  # Customer ID
    valueType: json  # Order details

  enriched_orders:
    topic: orders_with_customer_data
    keyType: string  # Customer ID
    valueType: json  # Combined order and customer data

tables:
  customers:
    topic: customer_data
    keyType: string  # Customer ID
    valueType: json  # Customer details

functions:
  join_order_with_customer:
    type: valueJoiner
    code: |
      # Combine order and customer information
      result = {}

      # Add order details
      if value1 is not None:
        result.update(value1)

      # Add customer details
      if value2 is not None:
        result["customer"] = value2

      new_value = result
    expression: new_value
    resultType: json

pipelines:
  enrich_orders:
    from: orders
    via:
      - type: join
        table: customers
        valueJoiner: join_order_with_customer
      - type: peek
        forEach:
          code: log.info("ENRICHED ORDER - key={}, order_id={}, customer={}", key, value.get("order_id"), value.get("customer", {}).get("name"))
    to: enriched_orders