# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/heads/release/1.0.x/docs/ksml-language-spec.json

# Producer for circuit breaker tutorial - generates API requests designed to trigger circuit breaker

functions:
  generate_circuit_breaker_requests:
    type: generator
    globalCode: |
      import random
      counter = 0
      # Higher ratio of failing requests to demonstrate circuit breaker
      request_types = ["normal_service", "failing_service", "failing_service", "normal_service", "failing_service"]
    code: |
      global counter, request_types
      counter += 1
      
      # Generate requests with pattern to trigger circuit breaker
      request_type = request_types[(counter - 1) % len(request_types)]
      
      request = {
        "request_id": f"req_{counter:04d}",
        "type": request_type,
        "service": "external_api",
        "timestamp": counter * 1000
      }
      
      # Add specific data based on request type
      if request_type == "normal_service":
        request["data"] = f"normal_payload_{counter}"
        request["expected_success"] = True
      else:  # failing_service
        request["data"] = f"failing_payload_{counter}"
        request["expected_failure"] = True
      
      key = f"req_{counter:04d}"
    expression: (key, request)
    resultType: (string, json)

producers:
  circuit_breaker_producer:
    generator: generate_circuit_breaker_requests
    interval: 2s
    to:
      topic: api_requests
      keyType: string
      valueType: json