streams:
  sales_input:
    topic: sales_data
    keyType: string
    valueType: json

functions:
  format_sales_report:
    type: keyValuePrinter
    code: |
      if value is None:
        return f"ERROR: Sale {key} has no data"
      
      # Extract sale information
      product = value.get("product", "Unknown")
      customer = value.get("customer", "Unknown")
      amount = value.get("amount", 0)
      quantity = value.get("quantity", 0)
      region = value.get("region", "Unknown")
      
      # Create formatted sales report
      return f"SALE REPORT | ID: {key} | Customer: {customer} | Product: {product} | Qty: {quantity} | Amount: ${amount:.2f} | Region: {region}"
    resultType: string

pipelines:
  print_sales:
    from: sales_input
    print:
      mapper: format_sales_report