functions:
  generate_temperature_message:
    type: generator
    globalCode: |
      import random
      sensorCounter = 0
    code: |
      global sensorCounter
      
      key = "sensor" + str(sensorCounter)         # Simulate 10 sensors "sensor0" to "sensor9"
      sensorCounter = (sensorCounter+1) % 10      # Increase the counter for next iteration
      
      value = {"temperature": random.randrange(150)}
    expression: (key, value)                      # Return a message tuple with the key and value
    resultType: (string, json)                    # Indicate the type of key and value

producers:
  # Produce a temperature message every 3 seconds
  temperature_producer:
    generator: generate_temperature_message
    interval: 3s
    to:
      topic: temperature_data
      keyType: string
      valueType: json
