functions:
  generate_binary_message:
    type: generator
    globalCode: |
      import random
      counter = 0
    code: |
      global counter
      
      key = "msg" + str(counter)
      counter = (counter + 1) % 100
      
      # Create simple binary message as list of bytes
      value = [
        counter % 256,                    # Counter byte
        random.randrange(0, 256),         # Random byte
        ord('K'),                         # ASCII 'K'
        ord('S'),                         # ASCII 'S'
        ord('M'),                         # ASCII 'M'
        ord('L'),                         # ASCII 'L'
        random.randrange(0, 256)          # Another random byte
      ]
      
      log.info("Generated binary message: key={}, bytes={}", key, value)
    expression: (key, value)
    resultType: (string, bytes)

producers:
  binary_producer:
    generator: generate_binary_message
    interval: 3s
    to:
      topic: ksml_sensordata_binary
      keyType: string
      valueType: bytes
