functions:
  generate_sensordata_message:
    type: generator
    globalCode: |
      import time
      import random
      sensorCounter = 0
    code: |
      global sensorCounter
      
      key = "sensor"+str(sensorCounter)           # Set the key to return ("sensor0" to "sensor9")
      sensorCounter = (sensorCounter+1) % 10      # Increase the counter for next iteration
      
      # Generate data matching SensorData.csv schema
      # Schema: name,timestamp,value,type,unit,color,city,owner
      value = {
        "name": key,
        "timestamp": str(round(time.time()*1000)),
        "value": str(random.randrange(0, 100)),
        "type": random.choice(["TEMPERATURE", "HUMIDITY", "PRESSURE"]),
        "unit": random.choice(["C", "F", "%", "Pa"]),
        "color": random.choice(["black", "blue", "red", "yellow", "white"]),
        "owner": random.choice(["Alice", "Bob", "Charlie", "Dave", "Evan"]),
        "city": random.choice(["Amsterdam", "Utrecht", "Rotterdam", "The Hague", "Eindhoven"])
      }
    expression: (key, value)                      # Return a message tuple with the key and value
    resultType: (string, json)                    # Generate as JSON, KSML will convert to CSV

producers:
  # Produce CSV sensor data messages every 3 seconds
  sensordata_csv_producer:
    generator: generate_sensordata_message
    interval: 3s
    to:
      topic: ksml_sensordata_csv
      keyType: string
      valueType: csv:SensorData                  # KSML will convert JSON to CSV format