functions:
  generate_sensordata_message:
    type: generator
    globalCode: |
      import time
      import random
      sensorCounter = 0
    code: |
      global sensorCounter
      
      key = "sensor"+str(sensorCounter)           # Set the key to return ("sensor0" to "sensor9")
      sensorCounter = (sensorCounter+1) % 10      # Increase the counter for next iteration
      
      # Generate data matching SensorData.xsd schema
      value = {
        "name": key,
        "timestamp": round(time.time()*1000),     # timestamp as long, not string
        "value": str(random.randrange(0, 100)),
        "type": random.choice(["TEMPERATURE", "HUMIDITY", "PRESSURE"]),
        "unit": random.choice(["C", "F", "%", "Pa"]),
        "color": random.choice(["black", "blue", "red", "yellow", "white"]),
        "city": random.choice(["Amsterdam", "Utrecht", "Rotterdam", "The Hague", "Eindhoven"]),
        "owner": random.choice(["Alice", "Bob", "Charlie", "Dave", "Evan"])
      }
    expression: (key, value)                      # Return a message tuple with the key and value
    resultType: (string, json)                    # Generate as JSON, KSML will convert to XML

producers:
  # Produce XML sensor data messages every 3 seconds
  sensordata_xml_producer:
    generator: generate_sensordata_message
    interval: 3s
    to:
      topic: ksml_sensordata_xml
      keyType: string
      valueType: xml:SensorData                   # KSML will convert JSON to XML format
