# This example shows how to read from a simple stream and output every message on stdout

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: forEach
    code: "print('key=' + str(key) + ', value=' + str(value))"

pipelines:
  main:
    from: sensor_source
    forEach: print_message
