# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/heads/main/docs/ksml-language-spec.json

# This example shows how to read from four simple streams and log all messages

streams:
  sensor_source_avro:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
    offsetResetPolicy: latest
  sensor_source_csv:
    topic: ksml_sensordata_csv
    keyType: string
    valueType: csv:SensorData
  sensor_source_json:
    topic: ksml_sensordata_json
    keyType: string
    valueType: json:SensorData
  sensor_source_protobuf:
    topic: ksml_sensordata_protobuf
    keyType: string
    valueType: protobuf:SensorDataProtobuf
  sensor_source_xml:
    topic: ksml_sensordata_xml
    keyType: string
    valueType: xml:SensorData

functions:
  # Log the message using the built-in log variable that is passed in from Java
  log_message:
    type: forEach
    parameters:
      - name: format
        type: string
    code: log.info("Consumed {} message - key={}, value={}", format, key, value)

pipelines:
  # Every pipeline logs its own message, passing in the format parameter to log_message above
  consume_avro:
    from: sensor_source_avro
    forEach:
      code: log_message(key, value, format="AVRO")
  consume_csv:
    from: sensor_source_csv
    forEach:
      code: log_message(key, value, format="CSV")
  consume_json:
    from: sensor_source_json
    forEach:
      code: log_message(key, value, format="JSON")
  consume_protobuf:
    from: sensor_source_protobuf
    forEach:
      code: log_message(key, value, format="PROTOBUF")
  consume_xml:
    from: sensor_source_xml
    forEach:
      code: log_message(key, value, format="XML")
