# This example shows how to read from a simple stream and copy every message to a target topic.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_copy:
    topic: ksml_sensordata_copy
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: forEach
    code: "print('key='+(key if isinstance(key,str) else str(key))+', value='+(value if isinstance(value,str) else str(value)))"

pipelines:
  # The main pipeline reads messages, outputs them and saves a copy in a target topic
  main:
    from: sensor_source
    via:
      - type: peek
        name: peek_and_print
        forEach: print_message
    to: sensor_copy

  # The secondary pipeline achieves the same results, but by inlining the target topic definition
  secondary:
    from: sensor_source
    to:
      topic: ksml_sensordata_copy
