# This example shows how to read from a simple stream and copy every message to a target topic.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_copy:
    topic: ksml_sensordata_copy
    keyType: string
    valueType: avro:SensorData

pipelines:
  # The main pipeline reads messages, outputs them and saves a copy in a target topic
  main:
    from: sensor_source
    via:
      - type: peek
        forEach:
          code: log.info("MAIN key={}, value={}", key, value)
    to: sensor_copy

  # The secondary pipeline does exactly the same, but by inlining the target topic definition instead of referencing
  # an earlier definition
  secondary:
    from: sensor_source
    via:
      - type: peek
        forEach:
          code: log.info("SECONDARY key={}, value={}", key, value)
    to:
      topic: ksml_sensordata_copy
