streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)
  sensor_filtered:
    topic: ksml_sensordata_filtered
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)

functions:
  print_message:
    type: forEach
    code: "print('key=' + str(key) + ', value=' + str(value))"

  filter_message:
    type: predicate
    code: |
      if value == None:
        return False
    expression: value["color"] == 'blue'

pipelines:
  main:
    from: sensor_source
    via:
      - type: filter
        name: filter_sensor
        predicate: filter_message
      - type: peek
        name: peek_and_print
        forEach: print_message
    to: sensor_filtered
