streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_filtered:
    topic: ksml_sensordata_filtered
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: forEach
    code: "print('key='+(key if isinstance(key,str) else str(key))+', value='+(value if isinstance(value,str) else str(value)))"

  filter_message:
    type: predicate
    expression: value["color"] == 'blue'

pipelines:
  main:
    from: sensor_source
    via:
      - type: filter
        name: filter_sensor
        predicate: filter_message
      - type: peek
        name: peek_and_print
        forEach: print_message
    to: sensor_filtered
