# $schema: https://axual.github.io/ksml/latest/ksml-language-spec.json

# This example shows how to filter messages from a simple stream. Here we
# only let "blue sensors" pass and discard other messages.

pipelines:
  filter_pipeline:
    from:
      topic: ksml_sensordata_avro
      keyType: string
      valueType: avro:SensorData
      offsetResetPolicy: latest
    via:
      - type: filter
        if:
          expression: value is not None and value["color"] != "blue"
    to:
      topic: ksml_sensordata_filtered
      keyType: string
      valueType: avro:SensorData
