streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_blue:
    topic: ksml_sensordata_blue
    keyType: string
    valueType: avro:SensorData
  sensor_red:
    topic: ksml_sensordata_red
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: forEach
    code: "print('SOURCE key=' + str(key) + ', value=' + str(value))"

pipelines:
  main:
    from: sensor_source
    via:
      - type: peek
        name: peek_and_print
        forEach: print_message
    branch:
      - if:
          expression: value != None and value['color'] == 'blue'
        to: sensor_blue
      - if:
          expression: value != None and value['color'] == 'red'
        to: sensor_red
      - forEach:
          code: |
            print('Unknown color sensor: '+str(value))
  red_flow:
    from: sensor_red
    forEach:
      type: forEach
      code: "print('RED key=' + str(key) + ', value=' + str(value))"
  blue_flow:
    from: sensor_blue
    forEach:
      type: forEach
      code: "print('BLUE key=' + str(key) + ', value=' + str(value))"
