# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/heads/release/1.0.x/docs/ksml-language-spec.json

# This example shows how to branch processing of messages from a simple stream. Here we fork processing of "blue
# sensors" and "red sensors" into a separate branch each. All other sensors will be processed in a default branch.
# Two separate pipelines act as validation of the branching logic, displaying what messages were sent to the blue
# and red topics.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
    offsetResetPolicy: latest
  sensor_blue:
    topic: ksml_sensordata_blue
    keyType: string
    valueType: avro:SensorData
  sensor_red:
    topic: ksml_sensordata_red
    keyType: string
    valueType: avro:SensorData

pipelines:
  main:
    from: sensor_source
    via:
      - type: peek
        forEach:
          code: log.info("SOURCE MESSAGE - key={}, value={}", key, value)
    branch:
      - if:
          expression: value is not None and value["color"] == "blue"
        to: sensor_blue
      - if:
          expression: value is not None and value["color"] == "red"
        to: sensor_red
      - forEach:
          code: log.warn("UNKNOWN COLOR - {}", value["color"] if value is not None else "None")

  blue_flow:
    from: sensor_blue
    forEach:
      code: log.info("FOUND BLUE SENSOR - key={}, value={}", key, value)

  red_flow:
    from: sensor_red
    forEach:
      code: log.info("FOUND RED SENSOR - key={}, value={}", key, value)
