streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_blue:
    topic: ksml_sensordata_blue
    keyType: string
    valueType: avro:SensorData
  sensor_red:
    topic: ksml_sensordata_red
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: generic
    code:

pipelines:
  main:
    from: sensor_source
    via:
      - type: peek
        name: peek_and_print
        forEach:
          code: log.info("SOURCE key={}, value={}", key, value)
    branch:
      - if:
          expression: value != None and value["color"] == "blue"
        to: sensor_blue
      - if:
          expression: value != None and value["color"] == "red"
        to: sensor_red
      - forEach:
          code: |
            log.warn("Unknown color: {}", value["color"])
  red_flow:
    from: sensor_red
    forEach:
      code: log.info("RED FLOW key={}, value={}", key, value)
  blue_flow:
    from: sensor_blue
    forEach:
      code: log.info("BLUE FLOW key={}, value={}", key, value)
