streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)
  sensor_0:
    topic: ksml_sensordata_sensor0
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)
  sensor_1:
    topic: ksml_sensordata_sensor1
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)
  sensor_2:
    topic: ksml_sensordata_sensor2
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)

functions:
  print_message:
    type: forEach
    code: "print('key=' + str(key) + ', value=' + str(value))"

pipelines:
  main:
    from: sensor_source
    via:
      - type: peek
        name: peek_and_print
        forEach: print_message
    toExtractor:
      code: |
        if key == 'sensor1':
          return 'ksml_sensordata_sensor1'
        elif key == 'sensor2':
          return 'ksml_sensordata_sensor2'
        else:
          return 'ksml_sensordata_sensor0'
