# This example shows how to route messages to a dynamic topic. The target topic is the result of an executed function.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_0:
    topic: ksml_sensordata_sensor0
    keyType: string
    valueType: avro:SensorData
  sensor_1:
    topic: ksml_sensordata_sensor1
    keyType: string
    valueType: avro:SensorData
  sensor_2:
    topic: ksml_sensordata_sensor2
    keyType: string
    valueType: avro:SensorData

pipelines:
  main:
    from: sensor_source
    via:
      - type: peek
        forEach:
          code: log.info("SOURCE MESSAGE - key={}, value={}", key, value)
    toExtractor:
      code: |
        if key == 'sensor1':
          return 'ksml_sensordata_sensor1'
        if key == 'sensor2':
          return 'ksml_sensordata_sensor2'
        return 'ksml_sensordata_sensor0'

  sensor0_flow:
    from: sensor_0
    forEach:
      code: log.info("SENSOR0 - key={}, value={}", key, value)

  sensor1_flow:
    from: sensor_1
    forEach:
      code: log.info("SENSOR1 - key={}, value={}", key, value)

  sensor2_flow:
    from: sensor_2
    forEach:
      code: log.info("SENSOR2 - key={}, value={}", key, value)
