# This example shows how to route messages to a dynamic topic. The target topic is the result of an executed function.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_0:
    topic: ksml_sensordata_sensor0
    keyType: string
    valueType: avro:SensorData
  sensor_1:
    topic: ksml_sensordata_sensor1
    keyType: string
    valueType: avro:SensorData
  sensor_2:
    topic: ksml_sensordata_sensor2
    keyType: string
    valueType: avro:SensorData

pipelines:
  main:
    from: sensor_source
    via:
      - type: peek
        forEach:
          code: log.info("key={}, value={}", key, value)
    toExtractor:
      code: |
        if key == 'sensor1':
          return 'ksml_sensordata_sensor1'
        elif key == 'sensor2':
          return 'ksml_sensordata_sensor2'
        else:
          return 'ksml_sensordata_sensor0'
