streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: forEach
    code: "print('key=' + str(key) + ', value=' + str(value))"

  doubleEveryRecord:
    type: keyValueToKeyValueListTransformer
    code: |
      if key == None:
        return []
    expression: "[(key+'-1',value),(key+'-2',value)]"
    resultType: "[(string,avro:SensorData)]"

pipelines:
  main:
    from: sensor_source
    via:
      - type: transformKeyValueToKeyValueList
        name: double_transform
        mapper: doubleEveryRecord
      - type: peek
        name: peek_and_print
        forEach: print_message
    toExtractor:
      code: |
        if key == 'sensor1':
          return 'ksml_sensordata_sensor1'
        elif key == 'sensor2':
          return 'ksml_sensordata_sensor2'
        else:
          return 'ksml_sensordata_sensor0'
