streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)
  sensor_0:
    topic: ksml_sensordata_sensor0
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)
  sensor_1:
    topic: ksml_sensordata_sensor1
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)
  sensor_2:
    topic: ksml_sensordata_sensor2
    keyType: nullable(string)
    valueType: nullable(avro:SensorData)

functions:
  print_message:
    type: forEach
    code: "print('key=' + str(key) + ', value=' + str(value))"

  doubleEveryRecord:
    type: keyValueToKeyValueListTransformer
    code: |
      if key == None:
        key = "dummy"
    expression: "[(key+'-1',value),(key+'-2',value)]"
    resultType: "[(nullable(string),nullable(avro:SensorData))]"

pipelines:
  main:
    from: sensor_source
    via:
      - type: transformKeyValueToKeyValueList
        name: double_transform
        mapper: doubleEveryRecord
      - type: peek
        name: peek_and_print
        forEach: print_message
    toExtractor:
      code: |
        if key == 'sensor1':
          return 'ksml_sensordata_sensor1'
        elif key == 'sensor2':
          return 'ksml_sensordata_sensor2'
        else:
          return 'ksml_sensordata_sensor0'
