streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData

functions:
  doubleThisRecord:
    type: keyValueToKeyValueListTransformer
    code: |
      if key == None:
        return []
    expression: "[(key+'-1',value),(key+'-2',value)]"
    resultType: "[(string,avro:SensorData)]"

pipelines:
  main:
    from: sensor_source
    via:
      - type: transformKeyValueToKeyValueList
        name: double_transform
        mapper: doubleThisRecord
      - type: peek
        forEach:
          code: log.info("key={}, value={}", key, value)
    toExtractor:
      code: |
        if key == 'sensor1':
          return 'ksml_sensordata_sensor1'
        elif key == 'sensor2':
          return 'ksml_sensordata_sensor2'
        else:
          return 'ksml_sensordata_sensor0'
