# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/heads/release/1.0.x/docs/ksml-language-spec.json

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
    offsetResetPolicy: latest

functions:
  double_this_record:
    type: keyValueToKeyValueListTransformer
    code: |
      if key is None:
        return []
    expression: "[(key+'-COPY1',value),(key+'-COPY2',value)]"
    resultType: "[(string,avro:SensorData)]"

pipelines:
  main:
    from: sensor_source
    via:
      - type: transformKeyValueToKeyValueList
        mapper: double_this_record
    forEach:
      code: log.info("GOT MESSAGE - key={}, value={}", key, value)
