# This example shows how to read from a simple stream, group by owner, apply windows and count owners per window.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_target:
    topic: ksml_sensordata_count
    keyType: avro:windowed(string)
    valueType: long

functions:
  print_message:
    type: forEach
    code: "print('key=' + str(key) + ', value=' + str(value))"

pipelines:
  main:
    from: sensor_source
    via:
      - type: groupBy
        name: ksml_sensordata_grouped
        mapper:
          expression: value["owner"]
          resultType: string
      - type: windowedBy
        windowType: time
        duration: 20s
        grace: 20s
      - type: count
        store:
          name: owner_count
          retention: 1h
          caching: false
      - type: toStream
      - type: convertKey
        into: avro:windowed(string)
      - type: peek
        forEach: print_message
    to: sensor_target
