# $schema: https://raw.githubusercontent.com/Axual/ksml/main/docs/ksml-language-spec.json

# This example shows how to read from a simple stream, group by owner, apply windows and count owners per window.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
    offsetResetPolicy: latest
  sensor_count:
    topic: ksml_sensordata_count
    keyType: avro:WindowedString
    valueType: long

pipelines:
  main:
    from: sensor_source
    via:
      - type: groupBy
        name: group_by_owner
        mapper:
          code: |
            if value is None or not "owner" in value:
              return "no owner"
          expression: value["owner"]
          resultType: string
      - type: windowByTime
        windowType: tumbling
        duration: 20s
        grace: 10d
      - type: count
        store:
          name: owner_count
          type: window
          windowSize: 10m
          retention: 1h
          caching: false
      - type: toStream
      - type: convertKey
        into: avro:windowed(string)
      - type: peek
        forEach:
          code: log.info("key={}, value={}", key, value)
    to: sensor_count
