# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/heads/release/1.0.x/docs/ksml-language-spec.json

# This example shows how to read from a simple stream, group by owner, apply windows and count owners per window.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
    offsetResetPolicy: latest

pipelines:
  main:
    from: sensor_source
    via:
      - type: groupBy
        name: group_by_owner
        mapper:
          code: |
            if value is None or not "owner" in value:
              return "no owner"
          expression: value["owner"]
          resultType: string
      - type: windowByTime
        windowType: tumbling
        duration: 20s
      - type: aggregate
        store:
          type: window
          windowSize: 10m
          retention: 1h
          caching: false
        initializer:
          expression: 0
          resultType: long
        aggregator:
          expression: aggregatedValue+1
          resultType: long
      - type: toStream
      - type: peek
        forEach:
          code: log.info("AGGREGATE - key={}, value={}", key, value)
