# This example shows how to read from a simple stream, group by owner, apply windows and count owners per window.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData

tables:
  sensor_target:
    topic: ksml_sensordata_table
    keyType: string
    valueType: avro:SensorData

pipelines:
  main:
    from: sensor_source
    via:
      - type: filter
        if:
          expression: key != None
      - type: peek
        forEach:
          code: log.info("STORED INTO TABLE key={}, value={}", key, value)
    to: sensor_target
