# $schema: https://axual.github.io/ksml/latest/ksml-language-spec.json

# This example shows how to read from a simple stream, filter records and store the results in a queryable table.

streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
    offsetResetPolicy: latest

tables:
  sensor_target:
    topic: ksml_sensordata_table
    keyType: string
    valueType: avro:SensorData

pipelines:
  main:
    from: sensor_source
    via:
      - type: filter
        if:
          expression: key is not None
      - type: peek
        forEach:
          code: log.info("STORED INTO TABLE key={}, value={}", key, value)
    to: sensor_target
