streams:
  - topic: ksml_sensordata_avro
    name: sensor_source
    keyType: string
    valueType: avro:SensorData
  - topic: ksml_sensordata_copy
    name: sensor_copy
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: forEach
    code: "print('key='+(key if isinstance(key,str) else str(key))+', value='+(value if isinstance(value,str) else str(value)))"

pipelines:
  main:
    from: ksml_sensordata_avro
    via:
      - type: peek
        name: peek_and_print
        forEach: print_message
    to: ksml_sensordata_copy
