streams:
  - topic: ksml_sensordata_avro
    name: sensor_source
    keyType: string
    valueType: avro:SensorData
  - topic: ksml_sensordata_sensor0
    name: sensor_0
    keyType: string
    valueType: avro:SensorData
  - topic: ksml_sensordata_sensor1
    name: sensor_1
    keyType: string
    valueType: avro:SensorData
  - topic: ksml_sensordata_sensor2
    name: sensor_2
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: forEach
    code: "print('key='+(key if isinstance(key,str) else str(key))+', value='+(value if isinstance(value,str) else str(value)))"

pipelines:
  main:
    from: sensor_source
    via:
      - type: peek
        name: peek_and_print
        forEach: print_message
    toExtractor:
      code: |
        if key == 'sensor1':
          return 'ksml_sensordata_sensor1'
        elif key == 'sensor2':
          return 'ksml_sensordata_sensor2'
        else:
          return 'ksml_sensordata_sensor0'
