streams:
  sensor_source:
    topic: ksml_sensordata_avro
    keyType: string
    valueType: avro:SensorData
  sensor_0:
    topic: ksml_sensordata_sensor0
    keyType: string
    valueType: avro:SensorData
  sensor_1:
    topic: ksml_sensordata_sensor1
    keyType: string
    valueType: avro:SensorData
  sensor_2:
    topic: ksml_sensordata_sensor2
    keyType: string
    valueType: avro:SensorData

functions:
  print_message:
    type: forEach
    code: "print('key='+(key if isinstance(key,str) else str(key))+', value='+(value if isinstance(value,str) else str(value)))"

pipelines:
  main:
    from: sensor_source
    via:
      - type: peek
        name: peek_and_print
        forEach: print_message
    toExtractor:
      code: |
        if key == 'sensor1':
          return 'sensor_1'
        elif key == 'sensor2':
          return 'sensor_2'
        else:
          return 'ksml_sensordata_sensor0'
