streams:
  product_clicks:
    topic: product_clicks
    keyType: string
    valueType: json

  product_purchases:
    topic: product_purchases
    keyType: string
    valueType: json

  correlated_user_actions:
    topic: correlated_user_actions
    keyType: string
    valueType: json

functions:
  correlate_click_and_purchase:
    type: valueJoiner
    code: |
      result = {}
      
      # Add click data
      if value1 is not None:
        result["click"] = value1
        
      # Add purchase data
      if value2 is not None:
        result["purchase"] = value2
        
      # Calculate conversion if both exist
      if value1 is not None and value2 is not None:
        result["converted"] = True
        click_time = value1.get("timestamp", 0)
        purchase_time = value2.get("timestamp", 0)
        result["conversion_time_ms"] = purchase_time - click_time
      else:
        result["converted"] = False
        
      return result

pipelines:
  match_clicks_with_purchases:
    from: product_clicks
    join:
      stream: product_purchases
      valueJoiner: correlate_click_and_purchase
      window:
        type: time
        size: 30m  # Look for purchases within 30 minutes of a click
    via:
      - type: peek
        forEach:
          code: log.info("CORRELATION - user={}, converted={}, click_product={}, purchase_product={}", key, value.get("converted"), value.get("click", {}).get("product_id"), value.get("purchase", {}).get("product_id"))
    to: correlated_user_actions