# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/heads/release/1.0.x/docs/ksml-language-spec.json

# This example demonstrates predefined state store configuration for counting sensors by owner

streams:
  sensor_source:
    topic: sensor_ownership_data
    keyType: string
    valueType: json
    offsetResetPolicy: latest
    
  owner_counts:
    topic: owner_sensor_counts
    keyType: string
    valueType: long

stores:
  owner_count_store:
    name: owner_count_store
    type: keyValue
    keyType: string
    valueType: long
    retention: 5m
    caching: false
    persistent: true
    logging: true

pipelines:
  count_by_owner:
    from: sensor_source
    via:
      - type: groupBy
        name: group_by_owner
        mapper:
          code: |
            if value is None:
              return "unknown"
            if not "owner" in value:
              return "unknown"
          expression: value["owner"]
          resultType: string
      - type: count
        store: owner_count_store
      - type: toStream
      - type: peek
        forEach:
          code: |
            log.info("PREDEFINED STORE - Owner: {}, sensor count: {}", key, value)
    to: owner_counts