streams:
  financial_transactions:
    topic: financial_transactions
    keyType: string  # account_id
    valueType: long  # transaction amount

  transaction_sums:
    topic: transaction_sums
    keyType: string
    valueType: long

functions:
  sum_amounts:
    type: reducer
    expression: value1 + value2
    resultType: long

pipelines:
  sum_transactions:
    from: financial_transactions
    via:
      - type: groupByKey
      - type: reduce
        reducer: sum_amounts
      - type: toStream
      - type: peek
        forEach:
          code: |
            log.info("Account {} total: {}", key, value)
    to: transaction_sums