pipelines:
  handle_out_of_order:
    from: input_stream
    via:
      - type: groupByKey
      - type: windowByTime
        windowType: tumbling
        size: 1h
        advanceBy: 1h
        grace: 15m  # Allow events up to 15 minutes late
      - type: aggregate
        initializer: initialize_pattern_state
        aggregator: update_pattern_state
    to: detected_patterns
