
from __future__ import annotations
from typing import Dict, Any, Optional, Union, List, Mapping, Protocol, Iterator

class KSMLLogger(Protocol):
    """KSML Logger with SLF4J-like interface"""

    def getName(self) -> str: ...

    # Level checks
    def isTraceEnabled(self) -> bool: ...
    def isDebugEnabled(self) -> bool: ...
    def isInfoEnabled(self) -> bool: ...
    def isWarnEnabled(self) -> bool: ...
    def isErrorEnabled(self) -> bool: ...

    # Trace logging
    def trace(self, s: str, *args: Any) -> None: ...

    # Debug logging
    def debug(self, s: str, *args: Any) -> None: ...

    # Info logging
    def info(self, s: str, *args: Any) -> None: ...

    # Warn logging
    def warn(self, s: str, *args: Any) -> None: ...

    # Error logging
    def error(self, s: str, *args: Any) -> None: ...

class CounterBridge(Protocol):
    """KSML Counter metric"""

    def increment(self) -> None: ...
    def increment(self, delta: int) -> None: ...

class MeterBridge(Protocol):
    """KSML Meter metric"""

    def mark(self) -> None: ...
    def mark(self, nrOfEvents: int) -> None: ...

class TimerBridge(Protocol):
    """KSML Timer metric"""

    def updateSeconds(self, valueSeconds: int) -> None: ...
    def updateMillis(self, valueMilliseconds: int) -> None: ...
    def updateNanos(self, valueNanoseconds: int) -> None: ...

class KSMLMetrics(Protocol):
    """KSML Metrics bridge for creating custom metrics"""

    def counter(self, name: str) -> CounterBridge: ...
    def counter(self, name: str, tags: Mapping[str, str]) -> CounterBridge: ...

    def meter(self, name: str) -> MeterBridge: ...
    def meter(self, name: str, tags: Mapping[str, str]) -> MeterBridge: ...

    def timer(self, name: str) -> TimerBridge: ...
    def timer(self, name: str, tags: Mapping[str, str]) -> TimerBridge: ...

class KSMLStateStore(Protocol):
    """Base interface for KSML state stores"""

    def name(self) -> str: ...
    def persistent(self) -> bool: ...
    def isOpen(self) -> bool: ...

class KSMLKeyValueStore(KSMLStateStore, Protocol):
    """KSML Key-Value store interface"""

    def get(self, key: Any) -> Optional[Any]: ...
    def put(self, key: Any, value: Any) -> None: ...
    def putIfAbsent(self, key: Any, value: Any) -> Optional[Any]: ...
    def delete(self, key: Any) -> Optional[Any]: ...
    def range(self, from_key: Any, to_key: Any) -> Iterator[Any]: ...
    def all(self) -> Iterator[Any]: ...
    def approximateNumEntries(self) -> int: ...

class KeyValueStore(KSMLStateStore, Protocol):
    """KSML Key-Value store interface"""

    def get(self, key: Any) -> Optional[Any]: ...
    def put(self, key: Any, value: Any) -> None: ...
    def putIfAbsent(self, key: Any, value: Any) -> Optional[Any]: ...
    def delete(self, key: Any) -> Optional[Any]: ...
    def range(self, from_key: Any, to_key: Any) -> Iterator[Any]: ...
    def all(self) -> Iterator[Any]: ...
    def approximateNumEntries(self) -> int: ...

# KSML runtime injected variables
log: KSMLLogger
metrics: KSMLMetrics
stores: Dict[str, Union[KSMLStateStore, KSMLKeyValueStore, Any]]
