
from __future__ import annotations
from typing import Dict, Any, Optional, Union, List, Mapping, Protocol, Iterator, TYPE_CHECKING

if TYPE_CHECKING:
    class PythonLogger(Protocol):
        """Logger with SLF4J-like interface (maps to io.axual.ksml.python.LoggerBridge.PythonLogger)"""

        def getName(self) -> str: ...

        # Level checks
        def isTraceEnabled(self) -> bool: ...
        def isDebugEnabled(self) -> bool: ...
        def isInfoEnabled(self) -> bool: ...
        def isWarnEnabled(self) -> bool: ...
        def isErrorEnabled(self) -> bool: ...

        # Trace logging
        def trace(self, s: str, *args: Any) -> None: ...

        # Debug logging
        def debug(self, s: str, *args: Any) -> None: ...

        # Info logging
        def info(self, s: str, *args: Any) -> None: ...

        # Warn logging
        def warn(self, s: str, *args: Any) -> None: ...

        # Error logging
        def error(self, s: str, *args: Any) -> None: ...

    class CounterBridge(Protocol):
        """KSML Counter metric"""

        def increment(self) -> None: ...
        def increment(self, delta: int) -> None: ...

    class MeterBridge(Protocol):
        """KSML Meter metric"""

        def mark(self) -> None: ...
        def mark(self, nrOfEvents: int) -> None: ...

    class TimerBridge(Protocol):
        """KSML Timer metric"""

        def updateSeconds(self, valueSeconds: int) -> None: ...
        def updateMillis(self, valueMilliseconds: int) -> None: ...
        def updateNanos(self, valueNanoseconds: int) -> None: ...

    class MetricsBridge(Protocol):
        """Metrics bridge for creating custom metrics (maps to io.axual.ksml.python.MetricsBridge)"""

        def counter(self, name: str) -> CounterBridge: ...
        def counter(self, name: str, tags: Mapping[str, str]) -> CounterBridge: ...

        def meter(self, name: str) -> MeterBridge: ...
        def meter(self, name: str, tags: Mapping[str, str]) -> MeterBridge: ...

        def timer(self, name: str) -> TimerBridge: ...
        def timer(self, name: str, tags: Mapping[str, str]) -> TimerBridge: ...

    class StateStore(Protocol):
        """Base interface for state stores"""

        def name(self) -> str: ...
        def persistent(self) -> bool: ...
        def isOpen(self) -> bool: ...

    class KeyValueStore(StateStore, Protocol):
        """Key-Value store interface"""

        def get(self, key: Any) -> Optional[Any]: ...
        def put(self, key: Any, value: Any) -> None: ...
        def putIfAbsent(self, key: Any, value: Any) -> Optional[Any]: ...
        def delete(self, key: Any) -> Optional[Any]: ...
        def range(self, from_key: Any, to_key: Any) -> Iterator[Any]: ...
        def all(self) -> Iterator[Any]: ...
        def approximateNumEntries(self) -> int: ...

    class SessionStore(StateStore, Protocol):
        """Session store interface"""

        def put(self, key: Any, value: Any) -> None: ...
        def remove(self, key: Any) -> None: ...
        def fetch(self, key: Any) -> Iterator[Any]: ...
        def fetchSession(self, key: Any, sessionStartTime: int, sessionEndTime: int) -> Any: ...
        def backwardFetch(self, key: Any) -> Iterator[Any]: ...
        def findSessions(self, key: Any, earliestSessionEndTime: int, latestSessionStartTime: int) -> Iterator[Any]: ...
        def backwardFindSessions(self, key: Any, earliestSessionEndTime: int, latestSessionStartTime: int) -> Iterator[Any]: ...

    class WindowStore(StateStore, Protocol):
        """Window store interface"""

        def put(self, key: Any, value: Any, windowStartTimestamp: int) -> None: ...
        def fetch(self, key: Any, timeFrom: int, timeTo: int) -> Iterator[Any]: ...
        def fetch(self, key: Any, timeFrom: Any, timeTo: Any) -> Iterator[Any]: ...
        def backwardFetch(self, key: Any, timeFrom: int, timeTo: int) -> Iterator[Any]: ...
        def fetchAll(self, timeFrom: int, timeTo: int) -> Iterator[Any]: ...
        def backwardFetchAll(self, timeFrom: int, timeTo: int) -> Iterator[Any]: ...
        def all(self) -> Iterator[Any]: ...
        def backwardAll(self) -> Iterator[Any]: ...

    class VersionedRecord(Protocol):
        """Versioned record returned by VersionedKeyValueStore"""

        def value(self) -> Any: ...
        def timestamp(self) -> int: ...

    class VersionedKeyValueStore(StateStore, Protocol):
        """Versioned Key-Value store interface"""

        def get(self, key: Any) -> Optional[VersionedRecord]: ...
        def get(self, key: Any, asOfTimestamp: int) -> Optional[VersionedRecord]: ...
        def put(self, key: Any, value: Any, timestamp: int) -> int: ...
        def delete(self, key: Any, timestamp: int) -> Optional[VersionedRecord]: ...

    # KSML runtime injected variables
    log: PythonLogger
    metrics: MetricsBridge
    stores: Dict[str, Union[StateStore, KeyValueStore, SessionStore, WindowStore, VersionedKeyValueStore, Any]]
else:
    # at runtime, make sure that the type hints do not cause any issues
    import java
    PythonLogger = java.type('io.axual.ksml.python.LoggerBridge$PythonLogger')
    MetricsBridge = java.type('io.axual.ksml.python.MetricsBridge')
    KeyValueStore = java.type('io.axual.ksml.store.KeyValueStoreProxy')
    SessionStore = java.type('io.axual.ksml.store.SessionStoreProxy')
    WindowStore = java.type('io.axual.ksml.store.WindowStoreProxy')
    VersionedKeyValueStore = java.type('io.axual.ksml.store.VersionedKeyValueStoreProxy')
    VersionedRecord = java.type('io.axual.ksml.store.VersionedRecordProxy')

