functions:
  generate_customer:
    type: generator
    globalCode: |
      import random
      customers_data = [
        {"id": "CUST001", "name": "Alice Johnson", "email": "alice@email.com", "region": "US-WEST"},
        {"id": "CUST002", "name": "Bob Smith", "email": "bob@email.com", "region": "US-EAST"},
        {"id": "CUST003", "name": "Carol Davis", "email": "carol@email.com", "region": "EU-WEST"},
        {"id": "CUST004", "name": "David Wilson", "email": "david@email.com", "region": "ASIA-PACIFIC"},
        {"id": "CUST005", "name": "Eva Brown", "email": "eva@email.com", "region": "EU-CENTRAL"}
      ]
      customer_index = 0
    code: |
      global customers_data, customer_index
      
      # Cycle through customers
      customer = customers_data[customer_index % len(customers_data)]
      customer_index += 1
      
      value = {
        "name": customer["name"],
        "email": customer["email"],
        "region": customer["region"],
        "status": "active"
      }
      
      key = customer["id"]
    expression: (key, value)
    resultType: (string, json)

producers:
  customer_producer:
    generator: generate_customer
    interval: 10s
    to:
      topic: customer_data
      keyType: string
      valueType: json