name: Build snapshot documentation on push to main
on:
  push:
    branches:
      - main
      - doc-rewrite
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: pages-deployment
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install mike
          pip install mkdocs-include-markdown-plugin
          pip install mkdocs-autorefs
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "deploy SNAPSHOT docs"
          git config --global user.email "development@axual.com"
      - name: Build Docs Site
        id: deployment
        run: |
          mike deploy --push --update-aliases DEVELOPMENT
