name: Maven Build and Test

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Name of the uploaded build artifact"
        value: ${{ jobs.build.outputs.artifact-name }}
  workflow_dispatch:

jobs:
  build:
    name: Build and test with GraalVM
    runs-on: ubuntu-latest
    outputs:
      artifact-name: build-artifacts-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch full history for SonarCloud analysis, because SonarCloud needs full git history to properly analyze changes.

      - name: Set up GraalVM
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '23'
          cache: 'maven'

      - name: Build and run all tests (unit + integration)
        run: |
          mvn clean verify -DskipITs=false --no-transfer-progress \
        # Only passes PR-specific properties when running on a pull request. On regular pushes to main, these evaluate to empty strings.
            ${{ github.event_name == 'pull_request' && format('-Dsonar.pullrequest.key={0}', github.event.pull_request.number) || '' }} \
            ${{ github.event_name == 'pull_request' && format('-Dsonar.pullrequest.branch={0}', github.head_ref) || '' }} \
            ${{ github.event_name == 'pull_request' && format('-Dsonar.pullrequest.base={0}', github.base_ref) || '' }}
        env:
          # TestContainers configuration for GitHub Actions
          TESTCONTAINERS_RYUK_DISABLED: false
          # SonarQube token - Maven profile auto-activates when set
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # GitHub token for SonarCloud PR decoration
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/target/surefire-reports/TEST-*.xml
            **/target/failsafe-reports/TEST-*.xml
          check_name: 'Publish Test Results'

      - name: Prepare build artifacts
        run: |
          mkdir -p build-output
          cp ksml-runner/target/ksml-runner*.jar build-output/
          cp -r ksml-runner/target/libs build-output/
          cp ksml-runner/NOTICE.txt build-output/
          cp LICENSE.txt build-output/

      - name: Upload build artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: build-output/
          retention-days: 7
