name: Package and Push Helm Chart
on:
  workflow_dispatch:
    inputs:
      app-version:
        required: true
        type: string
        description: "The app version that should be set in the chart"
      version:
        required: false
        default: 0.0.0-snapshot
        type: string
        description: "The version of the chart to be released"
  workflow_call:
    inputs:
      app-version:
        required: true
        type: string
      version:
        required: false
        default: 0.0.0-snapshot
        type: string

jobs:
  build-push-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

      - name: Checkout
        uses: actions/checkout@v5

      - name: Package Helm
        shell: bash
        run: |
          helm package --version '${{ inputs.version }}' --app-version '${{ inputs.app-version }}' ./packaging/helm-charts/ksml && ls ksml*.tgz

      - name: Login to registry
        shell: bash
        run: |
          helm registry login registry.axual.io/opensource/charts -u '${{ secrets.AXUAL_REGISTRY_USER }}' -p '${{ secrets.AXUAL_REGISTRY_TOKEN }}'

      - name: Push to registry
        shell: bash
        run: |
          helm push 'ksml-${{ inputs.version }}.tgz' oci://registry.axual.io/opensource/charts

      - name: Log out of registry
        shell: bash
        if: ${{ always() }}

        run: |
          helm registry logout registry.axual.io/opensource/charts &
