pipelines:
  edge_preprocessing:
    from: raw_sensor_readings
    via:
      - type: filter
        if:
          code: |
            # Only forward significant changes
            return value.get("readings", {}).get("temperature_change") > 0.5
      - type: transformValue
        mapper:
          code: |
            # Simplify payload for transmission
            return {
              "id": value.get("device_id"),
              "ts": value.get("timestamp"),
              "loc": value.get("location", {}).get("room"),
              "temp": value.get("readings", {}).get("temperature"),
              "hum": value.get("readings", {}).get("humidity")
            }
    to: edge_processed_readings
